name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y libgl-dev libxcursor-dev libpango1.0-dev libgdk-pixbuf-2.0-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev libasound2-dev libjack-jackd2-dev

    #   DISABLED FOR NOW UNTIL BUILDING WORKS ON LINUX
    #   - name: Build
    #     working-directory: ${{ github.workspace }}/src/app
    #     run: cargo xtask bundle hecto_drive --release

    #   - name: Test
    #     working-directory: ${{ github.workspace }}/src/app
    #     run: cargo test --verbose

    #   - name: Lint
    #     working-directory: ${{ github.workspace }}/src/app
    #     run: cargo clippy --all-targets --all-features -- -D warnings

    #   - name: Format
    #     working-directory: ${{ github.workspace }}/src/app
    #     run: cargo fmt --all -- --check
