name: TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/src/ui/package-lock.json

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/src/ui
        run: npm ci

      - name: Build
        working-directory: ${{ github.workspace }}/src/ui
        run: npm run build

      - name: Test
        working-directory: ${{ github.workspace }}/src/ui
        run: npm run test
    
      - name: Lint
        working-directory: ${{ github.workspace }}/src/ui
        run: npm run lint-check
    
      - name: Format
        working-directory: ${{ github.workspace }}/src/ui
        run: npm run format-check
